apiVersion: ENC[AES256_GCM,data:5Wk=,iv:kAM1DtHJrPFHy4/MgCe2qXkNicirQgTkfiG7VpClis8=,tag:zT2jdhhzEHA+2pf/zlEcUw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:0gl3n4cvzccCq5hd5O3nYgD5Bm6GCE9uFueOwdgwCtErOz1hvgNfN8MZansZoTpHXnviLV/cShtzlpY81bRxaI+XFNz2a5v77nfwaKl1mZVESVXSk8IeOh7x9uJEwtA69HhSkW4KNw+t21p2yz/ma14LCxG60rvg9Xo6x326v8dLoVlqCkmhjCEX7u/2j5zC7N7QkXNDwtM=,iv:085YghojnZW2etXAPUzPQpoi9juIT9nS9BV8tMsE4ow=,tag:q9WhZmSbJCSyC+hya1TMkg==,type:str]
kind: ENC[AES256_GCM,data:xy4e9OMw,iv:eqx5JsLuWbeTYdsMRPvkRaR+mj2f7ER+VJ2wBgcFtWQ=,tag:kY13QCuJ8ykt2ttHJ+T9Ng==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IcAkRM58Nfkm7szi1/9dlq/JArFPatcy,iv:tkKQt7faHV+jFACEpaR3Dl+oiiwq5Sg+O7gAJ8j07VI=,tag:BWPKWXtDSqO/xCq2JKHh/g==,type:str]
    namespace: ENC[AES256_GCM,data:vxEOoxwrQgJDNbo=,iv:oya5WvVk77PCjtgJRaVfK43O2x/AVU/I5GUpiK1zBkg=,tag:gJFMp1WJ6Saf3/qkDPaY1Q==,type:str]
type: ENC[AES256_GCM,data:xMaelt37Z38n3fUhyMAyvYsVp4JJuPoaGHiEAfF+,iv:7BIO/J1Jx6Gsen/Gx4p0rmzN9h/rG6j0ucEgGu1yJhc=,tag:7oeuUPBPqV09MSzxfFquJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u74ps32m3mcvd6zjaw8w2p3wwfucz0r2rxrsxmq8ldlyv5lapgkqle505u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMjllV21qVGEzV3BUekhq
            aE5HSDFMSUd0a1ZoZnRLd1J3N0RtbG40STBzCmRCTGZMamNLYUJ1eTZBMUhSTU5h
            VzVOeURjRXF1RUQ3SWFiSmxDSk9ZOW8KLS0tIC85Zm1YT3dpOWtWbGhraEtnTy94
            R1NHK0xyb1Z3T05iODhwTUZ1UER3S00K5qEi1RBFFruw0x94GSZLa2dGOPAV11x7
            nt/2s+glbh2jz1NArHkqUh3A4doxVpVhvnflwtGJw+OBYJoVEwMTyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-28T21:38:33Z"
    mac: ENC[AES256_GCM,data:Y0dtC14ILvmpQOBunlcGsp/UFN5tDYAR5RseGEKghnyCff1QydM16/xAkxR3p0cy7b8+SYUx5WnYFtTR5FddbunMShP2XEPdxX7EookClz3iatDcAxrC6g0xK7acZWuiei+RZbQmI25tZwvt3akP+ttbUmV4hHjhGwbnGhXCV60=,iv:FM1juT0bAeVMqlv45ZlMeyCe8hMQtbU+cdEv0KOU+rU=,tag:sNxh1ANdcyVSoVUhKj0DVA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
