---
tap_install:
  values: 
        shared:
          ca_cert_data: |
            -----BEGIN CERTIFICATE-----
            MIIGPDCCBCSgAwIBAgIUHVWasVbbE0Caoqpbc4cEWOySBhQwDQYJKoZIhvcNAQEL
            BQAwgZMxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJNQTEPMA0GA1UEBwwGQm9zdG9u
            MQ8wDQYDVQQKDAZWTXdhcmUxDjAMBgNVBAsMBVRhbnp1MS0wKwYDVQQDDCRteXJl
            cG8taGFyYm9yLmFrc2xhYjEudGFwLmZ5bmVzeS5jb20xFjAUBgkqhkiG9w0BCQEW
            B2FAYi5jb20wHhcNMjMwNjIzMTgyMzIyWhcNMjQwNjIyMTgyMzIyWjCBkzELMAkG
            A1UEBhMCVVMxCzAJBgNVBAgMAk1BMQ8wDQYDVQQHDAZCb3N0b24xDzANBgNVBAoM
            BlZNd2FyZTEOMAwGA1UECwwFVGFuenUxLTArBgNVBAMMJG15cmVwby1oYXJib3Iu
            YWtzbGFiMS50YXAuZnluZXN5LmNvbTEWMBQGCSqGSIb3DQEJARYHYUBiLmNvbTCC
            AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK7J5q6lMOZ0GF9fHDHcsUoM
            rt3eVg/Vm0giA3emFHTPvX2w7Cd5DN6sXyFVHzhZSrqfjH8BvUifswp1O34FF4JP
            3fnfyHT7vM/PVELOF6b6FKMhJT49Ty/7lrpiOf1QL2tP3ROQTtXWFNORqpyB1f/m
            2Y3Y1gyBNC4zQU6KxVwKKLJThmyzwI5r+gHghdhyAQ628qZ9cdAxn9kB3LQ9YDCc
            U71iX4HdAAKYsBJrnh7xwCl9kv+7EmJ3OJrR3OmHTcY4tpHhkhzju9EDcDkPagMm
            NighbfhfiESwR8khfTxHjWymYtTjj+Vg9BSqwEwiwXg/jN4nKkRErnYf6qf/MLIO
            ZudnryxjpHk/pIWj9MWnqJZI5WEqaP5G2IMfwmM2gmQm3xnj5AA6HLF1s9dJzro0
            ioS/u65WN13w9TBoq75VDPnQxSyVZz3SsCFkhENUD2TRdwU6GBuP18nSVTULUeLu
            /A8JF3+k3m1XKCZHsD7Hni8KDk8YAXPf7AG5U0I0vczPrHNH9x1///E+p0PY9Bus
            GqrmJZzYtaaSlITmdIHgFAYfchZ9mLy+AmVYzVPZjtvSM36iLtr1c8wsLScXQL3i
            +rmBSpoPpHL5s8oSsu6e4iAWWqec+BBVERFOsL4yR+OkiIH4t4p9hX3f7BtsTHiS
            +IZcg8rp0LdjqZKY3iQTAgMBAAGjgYUwgYIwHQYDVR0OBBYEFPH3XdQUBvH4RXo/
            UBYll+g9KJHXMB8GA1UdIwQYMBaAFPH3XdQUBvH4RXo/UBYll+g9KJHXMA8GA1Ud
            EwEB/wQFMAMBAf8wLwYDVR0RBCgwJoIkbXlyZXBvLWhhcmJvci5ha3NsYWIxLnRh
            cC5meW5lc3kuY29tMA0GCSqGSIb3DQEBCwUAA4ICAQB0/RpZmdYeh3UYZGJbbNZI
            25g3Z69yB4kQ77lRBMNFjLrxN+LvSdRE7IYlRSSJSSSgKx5WKXmYXWOsEgj4CSFz
            pIZZ7A5IBz4HhVz3EK+GFItsYDT+PbQfa2XCw8GNpYpFYf/Tjsbnc7E1RF5Wn+au
            B6DSHuO8nTroFw1WHHcB+KvF3ok9l27ov3/F646oGo5ua8mQuyDuIMY5U0ihH45m
            /VZu2dabrlWcg+gGIK8UOKvXLJW1MsRFHtD1qUIpIuBFnqTXzRY9zbmQ5ZGvt1Mt
            JBePtqYHCi1SijAzNFrsuQirZovxqctAetDzVnbnDKJZwJM6rarSRq45KnOLwfvM
            +N0Ch3cG0pvCuulMkeoqSkADMSTXkointI78E3N18i3oOq8AhymN3j6kHQqLUXxU
            4lUj17Fwj/+XHy3/lTVNacYj5fcr2JllNpIwXBstDXoDZxOcIAMs8k5yus0+buH3
            CroHQ6hyD8C5DAzE9nclnaFHYdHVm8yRaJEV1A62xTPa/Y/Aitqf/XhbwLB8+vuP
            LLVGhywP1eitkVH+lZ2M+eXS/pbBgH1F758DfQ7o1FU0z8jbPUmk7ASHzB2mYvGh
            3gMq3Em3D277qXoZ9v8JshmxWb8evjqj2DCMod8MlxRoHsL02Q1E1SqiSaM5jgKw
            Wy9MxXgNZz+MpibiFEM9sw==
            -----END CERTIFICATE-----




          ingress_domain: "akslab1.tap.fynesy.com"
          ingress_issuer: "letsencrypt-production"

          image_registry:
            project_path: myrepo-harbor.akslab1.tap.fynesy.com/library
            username: admin
            password: Harbor12345
        
        buildservice:
          kp_default_repository: myrepo-harbor.akslab1.tap.fynesy.com/library/build-service
          kp_default_repository_username: admin
          kp_default_repository_password: Harbor12345
        
        learningcenter:
            imageRegistry: 
              host: "myrepo-harbor.akslab1.tap.fynesy.com"
              username: admin
              password: Harbor12345


        ceip_policy_disclosed: true

        profile: full 
        supply_chain: basic 

        ootb_supply_chain_basic: 
          registry:
            server: "myrepo-harbor.akslab1.tap.fynesy.com"
            repository: "library"
          gitops:
            ssh_secret: ""

        contour:
          envoy:
            service:
              type: LoadBalancer 


        tap_gui:
          service_type: ClusterIP # If the shared.ingress_domain is set as earlier, this must be set to ClusterIP.
          metadataStoreAutoconfiguration: true 
          app_config:
            auth:
              allowGuestAccess: true
            catalog:
              locations:
                - type: url
                  target: http://github.com/tfynes-pivotal/tapblankcatalog/blob/main/catalog-info.yaml

        metadata_store:
          ns_for_export_app_cert: "*"
          app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.

        scanning:
          metadataStore:
            url: "" 

        grype:
          namespace: "default"
          targetImagePullSecret: "tap-registry"
          # In a single cluster, the connection between the scanning pod and the metadata store happens inside the cluster and does not pass through ingress. This is automatically configured, you do not need to provide an ingress connection to the store.

        policy:
          tuf_enabled: false 

        cnrs:
          domain_template: '{{.Name}}-{{.Namespace}}.{{.Domain}}'

        api_portal:
          apiPortalServer:
            #!sourceUrls: https://petstore.swagger.io/v2/swagger.json,http://10.0.166.161/openapi
            sourceUrls: https://petstore.swagger.io/v2/swagger.json,http://customer-profile-x.default.svc.cluster.local:8080/api-docs,http://scg-operator.tap-install.svc.cluster.local/openapi
            trustInsecureSourceUrls: true
            sourceUrlsCacheTtlSec: "30"
            sourceUrlsTimeoutSec: "30"
          sso:
            enabled: true
            secretName: sso-credentials
            apiManager:
              roles: tanzu.read
          apiKey:
            enabled: true
            vault:
              url: http://vault.vault.svc:8200/
              role: api-portal-role
              path: api-portal-for-vmware-tanzu
          serviceAccount:
            create: true
            name: api-portal

        namespace_provisioner:
          controller: false
          gitops_install:
            ref: origin/harbortest
            subPath: clusters/taplab/cluster-config/namespaces
            url: https://github.com/tfynes-pivotal/tap-gitops-sc2
          additional_sources:
          - git:
              ref: origin/harbortest
              subPath: clusters/taplab/cluster-config/namespaces/namespace-resources
              url: https://github.com/tfynes-pivotal/tap-gitops-sc2
            path: _ytt_lib/namespace-resources
        #!  import_data_values_secrets:
        #!   - name: my-dockerhub-credentials
        #!     namespace: tap-install
        #!     create_export: true
        package_overlays:
        - name: api-portal
          secrets:
          - name: api-portal-cm-tls-overlay-secret
          #!- name: reqfix-overlay-secret
        - name: accelerator
          secrets:
          - name: reqfix-overlay-secret
        - name: api-auto-registration
          secrets:
          - name: reqfix-overlay-secret
        - name: appliveview
          secrets:
          - name: reqfix-overlay-secret
        - name: appliveview-apiserver
          secrets:
          - name: reqfix-overlay-secret
        - name: appliveview-connector
          secrets:
          - name: reqfix-overlay-secret
        - name: appliveview-conventions
          secrets:
          - name: reqfix-overlay-secret
        - name: appsso
          secrets:
          - name: reqfix-overlay-secret
        - name: bitnami-services
          secrets:
          - name: reqfix-overlay-secret
        - name: buildservice
          secrets:
          - name: reqfix-overlay-secret
        - name: cartographer
          secrets:
          - name: reqfix-overlay-secret
        - name: cert-manager
          secrets:
          - name: reqfix-overlay-secret
        - name: cnrs
          secrets:
          - name: reqfix-overlay-secret
        - name: contour
          secrets:
          - name: reqfix-overlay-secret
        - name: crossplane
          secrets:
          - name: reqfix-overlay-secret
        - name: developer-conventions
          secrets:
          - name: reqfix-overlay-secret
        - name: eventing
          secrets:
          - name: reqfix-overlay-secret
        - name: fluxcd-source-controller
          secrets:
          - name: reqfix-overlay-secret
        - name: grype
          secrets:
          - name: reqfix-overlay-secret
        - name: learningcenter
          secrets:
          - name: reqfix-overlay-secret
        - name: learningcenter-workshops
          secrets:
          - name: reqfix-overlay-secret
        - name: metadata-store
          secrets:
          - name: reqfix-overlay-secret
        - name: namespace-provisioner
          secrets:
          - name: reqfix-overlay-secret
        - name: ootb-delivery-basic
          secrets:
          - name: reqfix-overlay-secret
        - name: ootb-supply-chain-basic
          secrets:
          - name: reqfix-overlay-secret
        - name: ootb-templates
          secrets:
          - name: reqfix-overlay-secret
        - name: policy-controller
          secrets:
          - name: reqfix-overlay-secret
        - name: scanning
          secrets:
          - name: reqfix-overlay-secret
        - name: service-bindings
          secrets:
          - name: reqfix-overlay-secret
        - name: services-toolkit
          secrets:
          - name: reqfix-overlay-secret
        - name: source-controller
          secrets:
          - name: reqfix-overlay-secret
        - name: spring-boot-conventions
          secrets:
          - name: reqfix-overlay-secret
        - name: tap-auth
          secrets:
          - name: reqfix-overlay-secret
        - name: tap-gui
          secrets:
          - name: reqfix-overlay-secret
        - name: tap-telemetry
          secrets:
          - name: reqfix-overlay-secret
        - name: tekton-pipelines
          secrets:
          - name: reqfix-overlay-secret

