---
tap_install:
  values: 
        shared:
          ca_cert_data: |
            -----BEGIN CERTIFICATE-----
            MIIGDDCCA/SgAwIBAgIULG1/58NRihto9FDrSCIYY4XLUM8wDQYJKoZIhvcNAQEL
            BQAwezELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk1BMQ8wDQYDVQQHDAZCb3N0b24x
            DjAMBgNVBAoMBVRhbnp1MQ4wDAYDVQQLDAVUYW56dTEWMBQGA1UEAwwNbXlyZXBv
            LWhhcmJvcjEWMBQGCSqGSIb3DQEJARYHYUBiLmNvbTAeFw0yMzA2MjMxNTE5MTBa
            Fw0yNDA2MjIxNTE5MTBaMHsxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJNQTEPMA0G
            A1UEBwwGQm9zdG9uMQ4wDAYDVQQKDAVUYW56dTEOMAwGA1UECwwFVGFuenUxFjAU
            BgNVBAMMDW15cmVwby1oYXJib3IxFjAUBgkqhkiG9w0BCQEWB2FAYi5jb20wggIi
            MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC2cxG6PuzFpzCLGH148oaHql7I
            09gapFCJqqvKatIDEFTr/Fb0J6FUf68S9Lu0jvOg0LSI3IUwq5eT7+JYuapIa4i/
            c5kYWo8hcir/0BkHKxTow40fN0G4J4mPEbEm2ZjhYP0jAcP+0FXAwmdTiiABKdlG
            17Cda4IPdt5DLlsRthXMyaZNn06VXr8emPezpF5UXXoZTdpnyhUQ1BfeTAOCxwp0
            eAnG/k5463LyXP3CCKOEOGsnRl24EuafxS30OpmTPun0N24DEqd6oLrvQ676DMCO
            10hHWU/LZQv/Hkrs0VeRKG4NPx19f0dFPKIlS54/1RCStumiFgiJcz8mzq6vscrn
            n+xMPziVkcJtdXnoSbKLAw/pEF7rzx8PVEfIIfkKpqZwGEdzDTR+V5n0TvHldtY9
            1xY2z6GBpUKpxNgEy/JG7s0XOBqk6gUEWBKpWBRaGJALbLpHW49q7k2s6J1bVbQ2
            zqbnLHOh17VBLZxYVT/FVd0vhpDBEPdH8vvymXjoQrj6NPZKEMqt+yMjAuZ10Qhi
            bmDL8wpMkF2FvSnqdXdHuwyGb2AruJFmz9eo05pnVSwuvXsk/edVPDGTUd9Mx3h3
            moUloNvI/sk36IoIuy/jUC7mL2twX5l7Qn283MZ90k5Eo+Bc64RnG+0YPHnyuYxC
            gAfIDduUli2wODTCSQIDAQABo4GHMIGEMB0GA1UdDgQWBBSfu51pgMd9L0I2js5v
            Bx3G/jLt+zAfBgNVHSMEGDAWgBSfu51pgMd9L0I2js5vBx3G/jLt+zAPBgNVHRMB
            Af8EBTADAQH/MDEGA1UdEQQqMCiCJm15cmVwby1oYXJib3IuaGFyYm9yLnN2Yy5j
            bHVzdGVyLmxvY2FsMA0GCSqGSIb3DQEBCwUAA4ICAQCc9cHqWlHL0MuPVh9Uo1LP
            RNtRWvFy5bBJm0g9ApqL5+JGujt6d6TXulGptxCHwWWzQXPo61GfHuE+GWp1pmKa
            kf9PjHQGd59Tj1crduEqgTZWFbzsJzTfkJSFuPMAQWqlAlFY/2/MndtfOc89BbAA
            +DW81XoUf6Pz1rVUJUQNou5GcCkwPUcLinVk4lTQGx3+2tsBKjeFM4zQEkQ9mRNl
            Jsa/c05KoakBtoEmXx75NoPDvYm84s6uOg4kOVWWOw4/vfIU71KNApcae39b39H0
            TE9cAgZ/7fbzbet9meKPqHbcRbThsApzeiYQoRPBy0j/ptdNen6PNEtw48wYWOxC
            MCJ+s87voyxOc8csC6os/izS3RmXUNKSnUdhmTUNS+NyhbDeVT8DXvyax6+18HHG
            V3trhjijfJPup7HKtAwPBCh49bx+6anYPfFyQRajHRUrCO0w+7WqDOj+ee4Rk+6Y
            NIyGVRE0kAgUROfkn+s8DaNyK1D9hhegUE9N38fibqnM8q84ww19gn2nVzO02MmT
            9InMhJrpS2yDz+sO+yoTfYdF1O5mzby0J3ZUelWmugJKVEvh953i4pUhpVEYRSIC
            m6Y365e3Mk9Xy8m2xe2AIsR8CXvL/k5g/sk9mp6aKQllb7eiLLC3mHqn44V9vtSm
            vlh3KrFgh+Zaj8rZfYeJoA==
            -----END CERTIFICATE-----


          ingress_domain: "akslab1.tap.fynesy.com"
          ingress_issuer: "letsencrypt-production"

          image_registry:
            project_path: myrepo-harbor.harbor.svc.cluster.local/tap
            username: admin
            password: Harbor12345
        
        buildservice:
          kp_default_repository: myrepo-harbor.harbor.svc.cluster.local/library/build-service
          kp_default_repository_username: admin
          kp_default_repository_password: Harbor12345
        
        learningcenter:
            imageRegistry: 
              host: "myrepo-harbor.harbor.svc.cluster.local"
              username: admin
              password: Harbor12345


        ceip_policy_disclosed: true

        profile: full 
        supply_chain: basic 

        ootb_supply_chain_basic: 
          registry:
            server: "myrepo-harbor.harbor.svc.cluster.local"
            repository: "tap"
          gitops:
            ssh_secret: ""

        ootb_supply_chain_testing_scanning:
          registry:
            server: "index.docker.io"
            repository: "fynesy"
          gitops:
            ssh_secret: ""

        contour:
          envoy:
            service:
              type: LoadBalancer 


        tap_gui:
          service_type: ClusterIP # If the shared.ingress_domain is set as earlier, this must be set to ClusterIP.
          metadataStoreAutoconfiguration: true 
          app_config:
            auth:
              allowGuestAccess: true
            catalog:
              locations:
                - type: url
                  target: http://github.com/tfynes-pivotal/tapblankcatalog/blob/main/catalog-info.yaml

        metadata_store:
          ns_for_export_app_cert: "*"
          app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.

        scanning:
          metadataStore:
            url: "" 

        grype:
          namespace: "default"
          targetImagePullSecret: "tap-registry"
          # In a single cluster, the connection between the scanning pod and the metadata store happens inside the cluster and does not pass through ingress. This is automatically configured, you do not need to provide an ingress connection to the store.

        policy:
          tuf_enabled: false 

        cnrs:
          domain_template: '{{.Name}}-{{.Namespace}}.{{.Domain}}'

        api_portal:
          apiPortalServer:
            #!sourceUrls: https://petstore.swagger.io/v2/swagger.json,http://10.0.166.161/openapi
            sourceUrls: https://petstore.swagger.io/v2/swagger.json,http://customer-profile-x.default.svc.cluster.local:8080/api-docs,http://scg-operator.tap-install.svc.cluster.local/openapi
            trustInsecureSourceUrls: true
            sourceUrlsCacheTtlSec: "30"
            sourceUrlsTimeoutSec: "30"
          sso:
            enabled: true
            secretName: sso-credentials
            apiManager:
              roles: tanzu.read
          apiKey:
            enabled: true
            vault:
              url: http://vault.vault.svc:8200/
              role: api-portal-role
              path: api-portal-for-vmware-tanzu
          serviceAccount:
            create: true
            name: api-portal

        namespace_provisioner:
          controller: false
          gitops_install:
            ref: origin/harbortest
            subPath: clusters/taplab/cluster-config/namespaces
            url: https://github.com/tfynes-pivotal/tap-gitops-sc2
          additional_sources:
          - git:
              ref: origin/harbortest
              subPath: clusters/taplab/cluster-config/namespaces/namespace-resources
              url: https://github.com/tfynes-pivotal/tap-gitops-sc2
            path: _ytt_lib/namespace-resources
        #!  import_data_values_secrets:
        #!   - name: my-dockerhub-credentials
        #!     namespace: tap-install
        #!     create_export: true
        package_overlays:
        - name: api-portal
          secrets:
          - name: api-portal-cm-tls-overlay-secret
          #!- name: reqfix-overlay-secret
        - name: accelerator
          secrets:
          - name: reqfix-overlay-secret
        - name: api-auto-registration
          secrets:
          - name: reqfix-overlay-secret
        - name: appliveview
          secrets:
          - name: reqfix-overlay-secret
        - name: appliveview-apiserver
          secrets:
          - name: reqfix-overlay-secret
        - name: appliveview-connector
          secrets:
          - name: reqfix-overlay-secret
        - name: appliveview-conventions
          secrets:
          - name: reqfix-overlay-secret
        - name: appsso
          secrets:
          - name: reqfix-overlay-secret
        - name: bitnami-services
          secrets:
          - name: reqfix-overlay-secret
        - name: buildservice
          secrets:
          - name: reqfix-overlay-secret
        - name: cartographer
          secrets:
          - name: reqfix-overlay-secret
        - name: cert-manager
          secrets:
          - name: reqfix-overlay-secret
        - name: cnrs
          secrets:
          - name: reqfix-overlay-secret
        - name: contour
          secrets:
          - name: reqfix-overlay-secret
        - name: crossplane
          secrets:
          - name: reqfix-overlay-secret
        - name: developer-conventions
          secrets:
          - name: reqfix-overlay-secret
        - name: eventing
          secrets:
          - name: reqfix-overlay-secret
        - name: fluxcd-source-controller
          secrets:
          - name: reqfix-overlay-secret
        - name: grype
          secrets:
          - name: reqfix-overlay-secret
        - name: learningcenter
          secrets:
          - name: reqfix-overlay-secret
        - name: learningcenter-workshops
          secrets:
          - name: reqfix-overlay-secret
        - name: metadata-store
          secrets:
          - name: reqfix-overlay-secret
        - name: namespace-provisioner
          secrets:
          - name: reqfix-overlay-secret
        - name: ootb-delivery-basic
          secrets:
          - name: reqfix-overlay-secret
        - name: ootb-supply-chain-basic
          secrets:
          - name: reqfix-overlay-secret
        - name: ootb-templates
          secrets:
          - name: reqfix-overlay-secret
        - name: policy-controller
          secrets:
          - name: reqfix-overlay-secret
        - name: scanning
          secrets:
          - name: reqfix-overlay-secret
        - name: service-bindings
          secrets:
          - name: reqfix-overlay-secret
        - name: services-toolkit
          secrets:
          - name: reqfix-overlay-secret
        - name: source-controller
          secrets:
          - name: reqfix-overlay-secret
        - name: spring-boot-conventions
          secrets:
          - name: reqfix-overlay-secret
        - name: tap-auth
          secrets:
          - name: reqfix-overlay-secret
        - name: tap-gui
          secrets:
          - name: reqfix-overlay-secret
        - name: tap-telemetry
          secrets:
          - name: reqfix-overlay-secret
        - name: tekton-pipelines
          secrets:
          - name: reqfix-overlay-secret

