---
apiVersion: v1
kind: Secret
metadata:
  name: tanzunet-registry
  namespace: harbor
  annotations:
    secretgen.carvel.dev/image-pull-secret: "tanzunet-registry"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K