apiVersion: v1
kind: Service
metadata:
  labels:
  name: customer_profile-x
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    carto.run/workload-name: customer_profile
  sessionAffinity: None
  type: ClusterIP