apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: customer-profile
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: customer-profile
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test-java
    - name: api-descriptor
      value:
        type: openapi
        location:
          path: "/api-docs"
        owner: "default-team"
        description: "test description"
  source:
    git:
      url: https://github.com/tfynes-pivotal/tjr1
      ref:
        branch: main
  serviceClaims:
    - name: database
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: postgres2-claim