apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: wf7
  Namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: wf7
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/tfynes-pivotal/wf7
      ref:
        branch: main
