#@ load("@ytt:overlay", "overlay")
#@ def tanzu_sync_app():
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: dependent-resources
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
#@ end

#@overlay/match by=overlay.subset(tanzu_sync_app())
---
spec:
  serviceAccountName: sync-sa
  fetch:
    - git:
        ref: origin/main
        url: https://github.com/tfynes-pivotal/tap-gitops-sc2
        subPath: clusters/akslab/cluster-config/dependent-resources
  template:
    #@overlay/match by=overlay.index(0)
    #@overlay/insert before=True
    - sops: 
        age:
          privateKeysSecretRef:
            name: sync-age-identity
  deploy:
    - kapp:
        rawOptions: ["--dangerous-allow-empty-list-of-resources=true"]
