#@ load("@ytt:json", "json")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")

#@ ca = """-----BEGIN CERTIFICATE-----
#@ MIIFnjCCA4agAwIBAgITKeIbVBZ/YZH9kKjo6OiBNbLFjzANBgkqhkiG9w0BAQ0F
#@ ADBfMQswCQYDVQQGEwJVUzELMAkGA1UECAwCTUExDzANBgNVBAcMBkJvc3RvbjEP
#@ MA0GA1UECgwGVm13YXJlMQ4wDAYDVQQLDAVUYW56dTERMA8GA1UEAwwIRnluZXN5
#@ Q0EwHhcNMjMwNjI4MTQxMjUxWhcNMzMwNjI1MTQxMjUxWjBfMQswCQYDVQQGEwJV
#@ UzELMAkGA1UECAwCTUExDzANBgNVBAcMBkJvc3RvbjEPMA0GA1UECgwGVm13YXJl
#@ MQ4wDAYDVQQLDAVUYW56dTERMA8GA1UEAwwIRnluZXN5Q0EwggIiMA0GCSqGSIb3
#@ DQEBAQUAA4ICDwAwggIKAoICAQDcFK1U9YqXfcuNF03Q44G/ItZ/9xCr6GvwZW9A
#@ XFBvLybQ1ykw8I7/VOoWSwhS9KZkc6Ea+HFuBK5xX8VK4hQUlIvR1D0z4EavSZtp
#@ 5sDtlpZzJRq4ETmGfyWDx9j98oj86hcrXB7jwKvTH92si1tO/JuauMeluQGMT6Cb
#@ orwCFiL/+LbizpRU+FLiPhuDv3A5WUb/YTk/TomJmxPIfaodyaRVwyiBOwoB8SjE
#@ ayojZgQPh7oTxdb7Gd/591Q4/A8VNGuOjrJI+hDZM/kiyQTxMb0F2uoA+4jyLfNK
#@ GQ9YyoTCnc5OxvldHfEi29hYQT73nI0f9XIlP/O39kBoMhrzCHEEY77gjx/fseSC
#@ 0/N1qAUqJWUSb6EV1uuf1tRatuSp8P1Zfd1okgpEYtankGpinfsCY5gTokRQN+nk
#@ 4HAWVn+A3SpoWXnJF7ZoCF+XsE2bOfrl0pD0N+2g/ON3SZsX7BQzS2LP1YB8Q97L
#@ kqj89NrtqfIDo3ZxEc4+TL90/KkkMe2xUsZBSPcy5xzocsNwjuSzuUetkUGBqbpx
#@ JmcGDflJtHIergK6lDYlMspTcxyOWz8id1y4OUUkHrvYE/WGqb+1WNlONs8ieHnH
#@ EJYh9m7Q/85MVJKneDZzkbXx+wOtV5MBE6RLAKd6Z4w6ftPMoZxOUForwhzQPre+
#@ CMJekwIDAQABo1MwUTAdBgNVHQ4EFgQUtG7LBS6QZq4vaOZSNAUZYlAX6zowHwYD
#@ VR0jBBgwFoAUtG7LBS6QZq4vaOZSNAUZYlAX6zowDwYDVR0TAQH/BAUwAwEB/zAN
#@ BgkqhkiG9w0BAQ0FAAOCAgEABfnPjXo80XKJWYhbxc8ctKMXojBm5lct12veMJ36
#@ ziPoiiRf90kUgziQ1Fr2Sn7pY6En5kKzGgWuZLS4SkI/3Za3AkjFg+uRZEss48PY
#@ uQWFOwnlYHu1wKKCFC/9POaXpOQwsYkkmW/bxwFU2mqAIkeqDtjt0ek9jFo9L2dI
#@ F0vCBkwHxp7mcezkEEvK1iviHAkvu637w8zzAZK5v+NSCtkpNYdPR5DsPVSYoAuc
#@ eBg61h3Nx+gaMvtPqDTO0+DIWyKDfdPafMSexieA28OCvCTuxWQXqg3Qb1C8eT+m
#@ ReVCmdkFVR3IZxblecHCA134/sF6dDG9C/gwH0i3wDk4f54/ErN7MxCCwrE755Rb
#@ AzjOLeNkgNwGGPMomDoX0036Zen1DP1v6IBYgu+xWh6F1gWmUwm4kvzEpyRxTuGI
#@ 1PkJp2rRPGfBcCSNx7yDdkN4mBj5YIsF7c35Yv14dDCNswdxmYpq6h9v/BJgrvVL
#@ qpIJkhMH6z4Ai3yl9UwNtOOu4p7v22UGudcepB/ydqAced+TwygYKA8L4exj4FDE
#@ LZ7bMh2ZbLWGc1P/rhzn9DeqOluHUbnPhHmQpRrnSArt4k87/MERupm0+VbrB22G
#@ NMp5wtZG6v7aYIF0YEYYKEOwX01+uJ1J4pumlrhWvSoTSnUpBY1rcqA7FF5YIRi+
#@ AYw=
#@ -----END CERTIFICATE-----
#@ """


apiVersion: v1
kind: Secret
metadata:
  name: custom-ca-trust-secret
  namespace: kube-system
type: Opaque
data:
  ca1.crt: #@ base64.encode(ca)