#@ load("@ytt:json", "json")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")

#@ crt =  """
#@ -----BEGIN CERTIFICATE-----
#@ MIIGLzCCBBegAwIBAgIUcKEz81VDubNs9AGaigZLWiC+Dz0wDQYJKoZIhvcNAQEN
#@ BQAwXzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk1BMQ8wDQYDVQQHDAZCb3N0b24x
#@ DzANBgNVBAoMBlZtd2FyZTEOMAwGA1UECwwFVGFuenUxETAPBgNVBAMMCEZ5bmVz
#@ eUNBMB4XDTIzMDYyODE0MTI1MloXDTMzMDYyNTE0MTI1MlowfDELMAkGA1UEBhMC
#@ VVMxCzAJBgNVBAgMAk1BMQ8wDQYDVQQHDAZCb3N0b24xDzANBgNVBAoMBlZtd2Fy
#@ ZTEOMAwGA1UECwwFVGFuenUxLjAsBgNVBAMMJSdteXJlcG8taGFyYm9yLmFrc2xh
#@ Yi50YXAuZnluZXN5LmNvbScwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC
#@ AQC6P/tyJ7JkI8tujJI0jJC6cs16/9tY8VFVoq4siOyV3mTe2iEIizd1wu9Ein9R
#@ 5+i/TV3cg0aPHbkb7XhsOWWh7p8WhSa2brYs3LkCmBx4LGzdtKMp0N0GEdXAG9ov
#@ 17eO7sb4ndZUL5btD9e6DjPKzEranY4RzlXqaj+aqMO38lyVjfvYXTUPAGZ1ALsX
#@ qFvec9Mq8oMQbJu2Ykp2FTIziM9rn09iWxVJN81NjTA3CXZ9Ohp23hc11014GppA
#@ 4thsIYzL2oOLyvaHq4W3AQe5is/TMDyIACsNTV+CD4VkFD8Gm8wyucp6EM3Qhjle
#@ hmqGR0nAaMp6f9LBj/sSYGdqG2SzfCrkt34A5TLljZES2pHhpKemCRrX9av2HBhv
#@ m5WJNPJg8Smwb8ruplw2YDU0TpP7g08h07v0XtBUgbA3Xz8wqrpJl9Qy82uabvBR
#@ sJu6n4lnFdRQWcn0IJlRwaLPSuNcuExNJGX4KvMWlhKErgEdUg2itMa9e2JhgiQL
#@ SOweEklLI1RIfIq01qzRI6b0JM3Aj9YA83rgeYN4dj/q/ofvjg/2Gw6VMR6ARdoM
#@ OcheiKQ9N6IT5qnr+aB5qg0I6xsnGiiKJgkGmoA0VfEPix0ocv/kIBePwkcNxwrN
#@ iGRzGatTeuP+LM1CJIxBe0fcy2hNQf5bg7xW790rTWyOEwIDAQABo4HFMIHCMB8G
#@ A1UdIwQYMBaAFLRuywUukGauL2jmUjQFGWJQF+s6MAkGA1UdEwQCMAAwCwYDVR0P
#@ BAQDAgTwMBMGA1UdJQQMMAoGCCsGAQUFBwMBMHIGA1UdEQRrMGmCDW15cmVwby1o
#@ YXJib3KCI215cmVwby1oYXJib3IuYWtzbGFiLnRhcC5meW5lc3kuY29tghcqLmFr
#@ c2xhYi50YXAuZnluZXN5LmNvbYIaKi5oYXJib3Iuc3ZjLmNsdXN0ZXIubG9jYWww
#@ DQYJKoZIhvcNAQENBQADggIBANHKK3rc9BfYM6/AzHihL569YCwOQwd3eEl3goxk
#@ SXk5GvfG9S/0AVbA93+P9s0rbCrIilstVB2BO7SG31eb4b93KsA9/1CGuIyrH330
#@ DPVr9UVBYFQLxMqQcdL85bcmQcOL+6mZ9sbhrJtu29t2Fpkqy7Ge8vrgChJB3S4C
#@ Ow3CFUp4RAY/ykdz7WuYt4luTNE+XscF3qrY9doCyqgYgHx16EHKW2sl4JcUBsLR
#@ R99UcV788Un/S6Aw0WpkerO0oYy/30cneTjLeZXsBTUS00B1l9Nw78GaYC5FH02e
#@ Aw0bQccxC2tNkbiML8hMkeUjyZFyG07tK+IGYS23INMcGwlMd5APOCbk4blWRGlM
#@ E47tI551zRPFmd8xMotCU7iNiJ5hC9WHCh05RPH5a9+Ia8EkuiSh1DtE99GqVdGF
#@ x08zd3LjcDASL6Jil6BOgDtdlIaFNKJCZm2bbtj7RCa0wbOWjj6/pPi1FIlllUzz
#@ I9Nzn+V+rca3gKlKvlSwvNhLoNWlX3uWmsepUz8peDMlLfvTRe/BvZGRRu6WKMvu
#@ 04r/367sd78OcEhIkHCWH8ynm9aJxSc2CG4WDq9e0J+SC7ODyWfbm1qbgwo++6Mr
#@ HgODjTEF32yKj4BTYaeN/ovkoyxHMnir8SKFyLtI/z9Bgs35Dv6AizU3jSt5ZFHW
#@ QVyJ
#@ -----END CERTIFICATE-----
#@ """

#@ key = "key"
#@ def getKey():
value: |
  this is 
  a test

return asString(value)
#@ end


apiVersion: v1
kind: Secret
metadata:
  name: harborcerts2
  namespace: harbor
type: kubernetes.io/tls
data:
  #@ encoded_crt = base64.encode(crt)
  #@ encoded_key = base64.encode(key)
  tls.crt: #@ base64.encode(encoded_crt)
  tls.key: #@ base64.encode(getKey().value)