#@ load("@ytt:data", "data")

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: harbor
  namespace: harbor
spec:
  packageRef:
    refName: spring-cloud-gateway.tanzu.vmware.com
  serviceAccountName: tap-install-sa
  values:
  - secretRef:
      name: tanzu-registry