#@ load("@ytt:json", "json")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")

#@ crt = 'admin'
#@ key = 'Harbor12345'

apiVersion: v1
kind: Secret
metadata:
  name: harborcerts2
  namespace: harbor
type: kubernetes.io/tls
data:
  #@ encoded_crt = base64.encode(crt)
  #@ encoded_key = base64.encode(key)
  tls.crt: #@ base64.encode(encoded_crt)
  tls.key: #@ base64.encode(encoded_key)